# Generated by Django 4.2.11 on 2024-04-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboRaw',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=45)),
                ('user_gender', models.CharField(max_length=10)),
                ('user_followers', models.CharField(default='0', max_length=45)),
                ('post_time', models.CharField(max_length=45)),
                ('thumbs_up', models.CharField(default='0', max_length=45)),
                ('comments', models.CharField(default='0', max_length=45)),
                ('reposts', models.CharField(default='0', max_length=45)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Weibo Raw1',
                'verbose_name_plural': 'Weibo Raws1',
                'db_table': 'weibo_raw1',
            },
        ),
    ]
