# Generated by Django 4.2.11 on 2024-04-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboTop10F',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('user_followers', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Weibo Top10Followers',
                'verbose_name_plural': 'Weibo Top10Followers',
                'db_table': 'weibo_top10f',
            },
        ),
    ]
