# Generated by Django 4.2.11 on 2024-04-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app', '0002_weibotop10f'),
    ]

    operations = [
        migrations.AddField(
            model_name='weiboraw',
            name='comments_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weiboraw',
            name='reposts_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weiboraw',
            name='thumbs_up_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weiboraw',
            name='user_followers_int',
            field=models.IntegerField(default=0),
        ),
    ]
