# Generated by Django 4.2.11 on 2024-04-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app', '0003_weiboraw_comments_int_weiboraw_reposts_int_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weiboraw',
            options={'ordering': ['id', 'userid', 'username', 'user_gender', 'user_followers', 'post_time', 'thumbs_up', 'reposts', 'comments', 'user_followers_int', 'thumbs_up_int', 'reposts_int', 'comments_int', 'content'], 'verbose_name': 'Weibo Raw1', 'verbose_name_plural': 'Weibo Raws1'},
        ),
    ]
