# Generated by Django 4.2.11 on 2024-04-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibo_app', '0004_alter_weiboraw_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weiboraw',
            options={'verbose_name': 'Weibo Raw1', 'verbose_name_plural': 'Weibo Raws1'},
        ),
    ]
